user_id: 123  # user id

webs:  # list of sites for parsing
  - http://www.rbc.ru
  - https://quote.ru/
  - https://vc.ru
  - https://ria.ru/
  - https://russian.rt.com/
  - https://aif.ru/
  - https://ren.tv/
  - https://lenta.ru/
  - https://iz.ru/
  - https://news.rambler.ru/
  - https://life.ru/
  - https://rg.ru/
key_words:  # list of keywords
  - ВСУ


stop_words:  # list of stopwords
  - слово1
  - слово2

frequency: 1  # the frequency of running the parser in hours