user_id: 123  # user id

webs:  # list of sites for parsing
#  - http://www.rbk.ru
  - https://quote.ru/

key_words:  # list of keywords
  - IPO
  - Газпром

stop_words:  # list of stopwords
  - слово1
  - слово2

frequency: 1  # the frequency of running the parser in hours

database:
  host: "localhost"
  user: "NewsScan"
  password: "Sql_9909"
  database: "NS_db"